### ISSUE TITLE
Pip pkg-resources==0.0.0

### ISSUE THREAD

**Issue by Benvii** [OpenPathView/DirectoryManager#1]
Got this error with pip install -r requirements.txt : 
`
Collecting pkg-resources==0.0.0 (from -r requirements.txt (line 11))
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 11)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 11))
`

**Comment by Valdimus** [comment]
Seem to be an issue in ubuntu:
http://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command
http://stackoverflow.com/questions/38992194/why-does-pip-freeze-list-pkg-resources-0-0-0
